### ISSUE TITLE
Setup CI and automatic publishing via GitHub Actions

### ISSUE THREAD

**Issue by parzhitsky** [parzh/observable-to-async-generator#5]
- [x] work is done mainly in `feature/*` branches (but it's not required)
- [x] ~~`master`~~ branch is renamed to `main`, and it's the default branch
- [x] pushing tags to `main` (`git push --follow-tags`) triggers a publish
- [x] check package versions in package.json and package-lock.json match
- [x] check version isn't published already (vacant)
- [x] build and test right before publish
- [x] test on linux, macos and windows

**Comment by parzhitsky** [comment]
Switched to tag-pushing-triggered publishes
